### ISSUE TITLE
Could not find interest points.

### ISSUE THREAD

**Issue by leonardoxie** [dshean/vmap#2]
Could not find interest points.

Traceback (most recent call last):
  File "vmap/vmap.py", line 510, in <module>
    main()
  File "vmap/vmap.py", line 408, in main
    run_cmd('stereo_corr', newopt+stereo_opt+stereo_args, msg='1.1: Low-res Correlation')
  File "vmap/vmap.py", line 41, in run_cmd
    raise Exception('Stereo step ' + kw['msg'] + ' failed')
Exception: Stereo step 1.1: Low-res Correlation failed

**Comment by dshean** [comment]
Can you provide more details on the input images?  Maybe a screenshot?  The low-res correlation can fail if the images don't have much contrast and/or not enough interest point matches are found on the downsampled versions of the images.

**Comment by atanutud** [comment]
![Untitled1](https://user-images.githubusercontent.com/111659523/185763630-c7dac3dc-16d4-4ebf-96dc-8d7f19c1167e.jpg)
![Untitled](https://user-images.githubusercontent.com/111659523/185763634-d431bd93-2388-489d-a1c4-2e4289c2bbbd.jpg)


PinholeStereoSession: unsupported camera file type.

Traceback (most recent call last):
  File "/home/hp/anaconda3/envs/vmap/bin/vmap.py", line 517, in <module>
    main()
  File "/home/hp/anaconda3/envs/vmap/bin/vmap.py", line 424, in main
    run_cmd('stereo_corr', newopt+stereo_opt+stereo_args, msg='1.1: Low-res Correlation')
  File "/home/hp/anaconda3/envs/vmap/bin/vmap.py", line 44, in run_cmd
    raise Exception('Stereo step ' + kw['msg'] + ' failed')
Exception: Stereo step 1.1: Low-res Correlation failed
